apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-secrets
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: ${{ secrets.AKS_IDENTITY_CLIENT_ID }} # Different from the Github actions client ID. Both must exist when running: az ad app list
    keyvaultName: "bhealth-vault"
    objects: |
      array:
        - objectName: "tf-generated-db-user"
          objectType: "secret"
        - objectName: "tf-generated-db-admin-password"
          objectType: "secret"
        - objectName: "tf-generated-db-host"
          objectType: "secret"
        - objectName: "tf-generated-db-name"
          objectType: "secret"
    tenantId: ${{ secrets.AZURE_TENANT_ID }}
