version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Europe/Madrid
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Europe/Madrid
  - package-ecosystem: "terraform"
    directory: "/infra"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: Europe/Madrid
  - package-ecosystem: "gomodules"
    directory: "/backend"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: Europe/Madrid
    labels:
      - "dependencies"
      - "go"