targets:
  $default:
    builders:
      freezed:
        enabled: true
        generate_for:
          exclude:
            - test
          include:
            - lib/models/**.dart
      json_serializable:
        options:
          explicit_to_json: true