name: health_monitor_app_flutter
description: A base flutter project for apps
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  chart_view: ^0.0.2
  collection: ^1.19.1
  dio: ^5.8.0+1
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.1
  go_router: ^14.8.1
  google_sign_in: ^6.2.2
  google_sign_in_ios: ^5.8.0
  intl: ^0.19.0
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  open_settings_plus: ^0.4.0
  path_provider: ^2.1.5
  riverpod_annotation: ^2.3.4
  shared_preferences: ^2.5.2
  slang: ^4.5.0
  slang_flutter: ^4.4.0
  syncfusion_flutter_charts: ^28.2.6
  widgetbook: ^3.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.5.8
  riverpod_generator: ^2.6.4
  build_runner: ^2.4.15
  custom_lint: ^0.7.2
  riverpod_lint: ^2.6.4
  json_serializable: ^6.9.4
  slang_build_runner: ^4.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/i18n/
    - assets/images/
    - ./.env.dev