apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-secrets
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "${user_assigned_identity_id}"
    keyvaultName: "${keyvault_name}"
    tenantId: "${tenant_id}"
    objects: |
      - objectName: tf-managed-db-user
        objectType: secret
      - objectName: tf-managed-db-admin-password
        objectType: secret
      - objectName: tf-managed-db-host
        objectType: secret
      - objectName: tf-managed-db-name
        objectType: secret
